<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Azure.AI.OpenAI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LlmMockService.Server\LlmMockService.Server.csproj" />
  </ItemGroup>

</Project>
